# ...existing code...
- Run "git filter-repo --invert-paths --paths app/node_modules/electron/dist/electron.exe --force"
+ Run "git filter-repo --invert-paths --path `"app/node_modules/electron/dist/electron.exe`" --force"
# ...existing code...